#!/bin/bash
#SBATCH -D .
#SBATCH --array=1-5 # Submitting 5 parallel jobs
#SBATCH --job-name=component_analysis
#SBATCH --output=slurm-%A_%a.out    # Change this line
#SBATCH --error=slurm-%A_%a.err     # Add this line
#SBATCH --clusters=cm4
#SBATCH --partition=cm4_tiny
#SBATCH --qos=cm4_tiny
#SBATCH --cpus-per-task=25
#SBATCH --time=24:00:00
#SBATCH --mail-type=NONE
#SBATCH --mail-user=Eesha.Chitnis@campus.lmu.de

# Activate Conda environment
source /etc/profile.d/modules.sh
source ~/.conda_init
module load slurm_setup
conda activate vim 

# Run Python script
python3 run_component.py $SLURM_ARRAY_TASK_ID 2>&1