#!/bin/bash
#SBATCH -p mcml-dgx-a100-40x8
#SBATCH --qos=mcml
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH -t 47:00:00

# Load your Python environment
source $(conda info --base)/etc/profile.d/conda.sh
conda activate vim  # Replace 'vim' with your actual conda environment name

# Ensure logs directory exists
mkdir -p logs

# Execute the Python script in the current directory
python3 submit4.py